"""Error-lifecycle instrumentation for LLM multi-agent systems."""

from .metrics import (
    AttestationCase,
    AttestationMetrics,
    RunMetrics,
    compute_metrics,
    summarize_attestations,
)
from .schema import (
    AccessPolicy,
    AgentSpec,
    AnnotationRecord,
    ArtifactKind,
    ArtifactOrigin,
    ArtifactRecord,
    AttestationRecord,
    AttestationStatus,
    AttestationVerdict,
    EdgeSpec,
    EvidenceRecord,
    EvidenceValidity,
    EventType,
    GraderRunRecord,
    InformationAssignmentRecord,
    InjectionRecord,
    JudgeSpec,
    LifecycleEvent,
    MessageRecord,
    ModelCallRecord,
    OutcomeKind,
    PromptRecord,
    RunManifest,
    RunOutcome,
    RunStatus,
    ToolCallRecord,
    ToolCallStatus,
    TruthStatus,
    VerificationCompletionStatus,
    VerificationTiming,
    VerificationVerdict,
)
from .store import TraceBundle, TraceValidationError, load_trace, write_trace

__all__ = [
    "AccessPolicy",
    "AgentSpec",
    "AnnotationRecord",
    "ArtifactKind",
    "ArtifactOrigin",
    "ArtifactRecord",
    "AttestationCase",
    "AttestationMetrics",
    "AttestationRecord",
    "AttestationStatus",
    "AttestationVerdict",
    "EdgeSpec",
    "EvidenceRecord",
    "EvidenceValidity",
    "EventType",
    "GraderRunRecord",
    "InformationAssignmentRecord",
    "InjectionRecord",
    "JudgeSpec",
    "LifecycleEvent",
    "MessageRecord",
    "ModelCallRecord",
    "OutcomeKind",
    "PromptRecord",
    "RunManifest",
    "RunMetrics",
    "RunOutcome",
    "RunStatus",
    "ToolCallRecord",
    "ToolCallStatus",
    "TraceBundle",
    "TraceValidationError",
    "TruthStatus",
    "VerificationCompletionStatus",
    "VerificationTiming",
    "VerificationVerdict",
    "compute_metrics",
    "load_trace",
    "summarize_attestations",
    "write_trace",
]

__version__ = "0.2.0"
